services:
  gateway:
    build: ../../gateway
    ports:
      - "8000:8000"

  user-service:
    build: ../../services/user_service
    ports:
      - "8001:8001"
    networks:
      - backend
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: user_service
      DB_USER: user_service
      DB_PASSWORD: user_service
    depends_on: 
      user-db: 
        condition: service_healthy

  user-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user_service"] 
      interval: 3s 
      timeout: 3s 
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend

  order-service:
    build: ../../services/order-service
    ports:
      - "8002:8002"

  payment-service:
    build: ../../services/payment-service
    ports:
      - "8003:8003"

networks: 
  backend: 
    driver: bridge
